---
name: Test

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'


jobs:
    test:
      strategy:
        matrix:
          go: ['1.19','1.18']
          platform: [ubuntu-latest]
      runs-on: ${{ matrix.platform}}
      steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: |
          go test -race -count=1 ./... -covermode=atomic  -coverprofile=coverage.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3